/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeedbackResponse } from '../models/feedback-response';
export interface PageResponseFeedbackResponse {
  first?: boolean;
  last?: boolean;
  list?: Array<FeedbackResponse>;
  number?: number;
  size?: number;
  totalElement?: number;
  totalPages?: number;
}
