/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookResponse } from '../models/book-response';
export interface PageResponseBookResponse {
  first?: boolean;
  last?: boolean;
  list?: Array<BookResponse>;
  number?: number;
  size?: number;
  totalElement?: number;
  totalPages?: number;
}
